version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/code"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/deployment"
    schedule:
      interval: "daily"
