name: Pizzacalc CI/CD

on:
  push:
    branches: [main]

  workflow_dispatch:

concurrency: deployment

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build project
        run: pnpm --filter pizzacalc build
      - name: Run tests
        run: pnpm --filter pizzacalc test:coverage
      - name: Lint and format check
        run: pnpm --filter pizzacalc check
      - name: CheckTs
        run: pnpm --filter pizzacalc checkTs
      - uses: actions/upload-artifact@v4
        with:
          name: build_merge_to_main
          path: code/build

  cdk_deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - uses: actions/download-artifact@v4
        with:
          name: build_merge_to_main
          path: code/build/
      - name: Run cdk deploy
        run: pnpm --filter deployment cdk deploy --require-approval never
        env:
          AWS_DEFAULT_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
