name: Pizzacalc CI PR

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn build
      - name: Run tests
        run: yarn test --coverage --watchAll=false
      - name: Run eslint
        run: yarn lint
      - name: CheckTs
        run: yarn checkTs
      - name: Prettify
        run: yarn prettify -c
